[[bin]]
name = 'joystream-node'
path = 'src/main.rs'

[package]
authors = ['Joystream']
build = 'build.rs'
edition = '2018'
name = 'joystream-node'
version = '2.0.0'

[dependencies]
hex-literal = '0.2.1'
derive_more = '0.14.0'
exit-future = '0.1.4'
futures = '0.1.29'
log = '0.4.8'
parking_lot = '0.9.0'
tokio = '0.1.22'
jsonrpc-core = '13.2.0'
rand = '0.7.2'
structopt = '0.3.3'
serde_json = '1.0'
serde = '1.0'
hex = '0.4'

[dependencies.substrate-basic-authorship]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-basic-authorship'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.babe]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-consensus-babe'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.babe-primitives]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-consensus-babe-primitives'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.codec]
package = 'parity-scale-codec'
version = '1.0.0'

[dependencies.ctrlc]
features = ['termination']
version = '3.0'

[dependencies.inherents]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-inherents'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.network]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-network'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.node-runtime]
package = 'joystream-node-runtime'
git = 'https://github.com/mnaamani/substrate-runtime-joystream'
rev = 'dc1a7b336a101d0c2b078cf89e77dc4478b34968' # working group integration

[dependencies.new-node-runtime]
package = 'joystream-node-runtime'
git = 'https://github.com/juniuszhou/substrate-runtime-joystream'
branch = 'data-migration'
# path = 'substrate-runtime-joystream'

[dependencies.primitives]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-primitives'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.sr-io]
git = 'https://github.com/paritytech/substrate.git'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.substrate-cli]
git = 'https://github.com/paritytech/substrate.git'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.substrate-client]
git = 'https://github.com/paritytech/substrate.git'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.substrate-executor]
git = 'https://github.com/paritytech/substrate.git'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.substrate-service]
git = 'https://github.com/paritytech/substrate.git'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.transaction-pool]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-transaction-pool'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.substrate-telemetry]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-telemetry'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.grandpa]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-finality-grandpa'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.grandpa-primitives]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-finality-grandpa-primitives'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.im-online]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-im-online'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.substrate-rpc]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-rpc'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.authority-discovery]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-authority-discovery'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.client-db]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-client-db'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.runtime-primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sr-primitives'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.offchain]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-offchain'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[profile.release]
panic = 'unwind'

[build-dependencies]
vergen = '3'
